name: Create PR in Different Repository

on:
  push:
    branches:
      - master

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Extract Branch Name
        shell: bash
        run: echo "BRANCH_NAME=$(git branch --merged | egrep -v '(^\*|master|main)')" >> $GITHUB_ENV
          
      - name: Setup GH CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          TARGET_REPO="pablohashescobar/closed-repo"
          TARGET_BRANCH="maintain"
          SOURCE_BRANCH="master"
          
          git checkout $SOURCE_BRANCH
          git remote add target "https://$GH_TOKEN@github.com/$TARGET_REPO.git"
          git push target $SOURCE_BRANCH
          
          gh pr create \
          --base $TARGET_BRANCH \
          --head $SOURCE_BRANCH \
          -t "Automated PR from" \
          -b "Automated PR created from ${{ github.repository }}/$SOURCE_BRANCH" \
          --repo $TARGET_REPO

