name: Create PR in Different Repository

on:
  push:
    branches:
      - master  # or the name of your default branch

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup GH CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Replace with your information
          TARGET_REPO="pablohashescobar/closed-repo"
          TARGET_BRANCH="master"
          SOURCE_BRANCH="${{ github.ref }}"
          
          git remote add target "https://x-access-token:$GH_TOKEN@github.com/$TARGET_REPO.git"
          git push target HEAD:$TARGET_BRANCH
          
          gh pr create \
            --base $TARGET_BRANCH \
            --head $SOURCE_BRANCH \
            --title "Automated PR" \
            --body "Automated PR created from ${{ github.repository }}" \
            --repo $TARGET_REPO \
            --token $GH_TOKEN